name: Build ECS

on:
  push:
    branches:
      # Automatically build master. Additional branches may be added.
      - master
  workflow_dispatch:
    # Allows manual build and deploy of any branch/ref

jobs:
  # Build and push container image to ECR. Builds occur in the project repository.
  build:
    name: Build
    uses: CruGlobal/.github/.github/workflows/build-ecs.yml@v1
    with:
      microservice-app: appbuilder
