name: Update Platform Version
# NOTE - this workflow is synced automatically. 
# Edit the template in planning/templates/services/merging-rules.yml
run-name: Update ab_platform_service to ${{ github.event.client_payload.version }}
on:
  repository_dispatch:
    types: [platform_new_version]
permissions:
  # Needed for the Update Sub Repo Job
  contents: write
jobs:
  call-update-sub:
    name: Update
    uses: digi-serve/.github/.github/workflows/update-sub-repo.yml@master
    secrets: 
      TOKEN:  ${{ secrets.GITHUB_TOKEN }}
    with:
      repository: digi-serve/appbuilder_platform_service
      short_name: platform
      folder: AppBuilder
      version: ${{ github.event.client_payload.version }}

  call-run-cy-test:
    name: Test
    needs: call-update-sub
    uses: digi-serve/.github/.github/workflows/cypress-e2e-tests.yml@master
    with:
      ref: ${{ needs.call-update-sub.outputs.branch }}

  call-generate-build-meta:
    name: Meta
    uses: digi-serve/.github/.github/workflows/generate-build-meta.yml@master
    with: 
      version: ${{ github.event.client_payload.version }}
      identifier: p

  call-bump-version:
    name: Version
    if: ${{ github.event.client_payload.type == 'minor' || github.event.client_payload.type == 'patch' }}
    needs: [ call-update-sub, call-run-cy-test, call-generate-build-meta ]
    uses: digi-serve/.github/.github/workflows/bump-version.yml@master
    with:
      ref: ${{ needs.call-update-sub.outputs.branch }}
      # Consider platform version updates as patch
      type: patch
      build_meta: ${{ needs.call-generate-build-meta.outputs.build }}

  call-merge-release:
    name: Merge
    needs: [ call-update-sub, call-bump-version ]
    uses: digi-serve/.github/.github/workflows/branch-merge-release.yml@master
    with: 
      branch: ${{ needs.call-update-sub.outputs.branch }}
      tag: v${{ needs.call-bump-version.outputs.new_version }}
      body: "- platform updated to v${{ github.event.client_payload.version }}"

  call-docker-build:
    uses: digi-serve/.github/.github/workflows/docker-build.yml@master
    needs: [ call-merge-release, call-bump-version]
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    with:
      base_tag: master
      tags: master,develop,${{ needs.call-bump-version.outputs.new_version }}

  call-dispatch-update:
    needs: [ call-docker-build, call-bump-version ]
    uses: digi-serve/.github/.github/dispatch-update.yml@master
    with:
      type: patch
      version: ${{ needs.call-bump-version.outputs.new_version }}
      app_id: ${{ vars.GS_DEV_APP_ID }}
    secrets:
      app_secret: ${{ secrets.GS_DEV_APP_PK }}

  call-open-pr-fail:
    name: Tests Failed
    needs: [ call-update-sub, call-run-cy-test ]
    if: ${{ failure() && github.event.client_payload.type != 'major' }}
    uses: digi-serve/.github/.github/workflows/open-pr.yml@master
    with: 
      branch: ${{ needs.call-update-sub.outputs.branch }}
      title: Update platform to ${{ github.event.client_payload.version }} (from GitHub Actions Workflow)
      body: Automatic updated failed. Check the [E2E tests](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}).
      release_notes: "- platform updated to ${{ github.event.client_payload.version }}"
  
  call-open-pr-major:
    name: Major Change
    needs: [ call-update-sub ]
    if: ${{ github.event.client_payload.type == 'major' }}
    uses: digi-serve/.github/.github/workflows/open-pr.yml@master
    with: 
      branch: ${{ needs.call-update-sub.outputs.branch }}
      title: Update platform to ${{ github.event.client_payload.version }} (from GitHub Actions Workflow)
      body: This is a major platform update. Please review and merge when ready.
      release_notes: "- platform updated to ${{ github.event.client_payload.version }}"
